#!/usr/bin/env python3.3

import sys, time, uuid, requests

endpoint = sys.argv[1]
now      = time.time()
key      = "test-" + uuid.uuid1().hex
url      = '%s/%s' % (endpoint, key)

print("testing with url %s..." % url)

def die(msg):
  sys.stdout.write("ERROR: %s\n" % msg)
  sys.exit(1)

def ok(msg):
  sys.stdout.write("OK: %s\n" % msg)

def parse(s):
  try:
    return float(s.strip())
  except:
    die('could not parse timestamp: %s' % s)

# test that new keys 404
r = requests.get(url)
r.status_code == 404 or die('get with new key returned status code: %s' % r.status_code)
ok('get with new key 404ed as expected')
